# -*- coding: utf-8 -*-
"""Cleaned Python Script

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fwZmDJq_EMHtNVBvgvmZK0SmnqnhaPYJ
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import xgboost as xgb
import shap
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings('ignore')

plt.rcParams['font.sans-serif'] = ['DejaVu Sans']
plt.rcParams['axes.unicode_minus'] = False

print("=== Step 1: Data Acquisition and Alignment ===")
df_weather = pd.read_csv('export (1).csv')
df_weather['date'] = pd.to_datetime(df_weather['date'])

df_weather = df_weather[['date', 'tavg', 'wspd', 'pres', 'prcp']]
df_weather.columns = ['Date', 'Temperature', 'WindSpeed', 'Pressure', 'Precipitation']

df_weather['Precipitation'] = df_weather['Precipitation'].fillna(0)
df_weather['WindSpeed'] = df_weather['WindSpeed'].fillna(0)
df_weather = df_weather.fillna(df_weather.mean(numeric_only=True))

df_aqi = pd.read_csv('perai-air-quality.csv')
df_aqi.columns = df_aqi.columns.str.strip().str.lower()
df_aqi['date'] = pd.to_datetime(df_aqi['date'])
df_aqi['pm25'] = pd.to_numeric(df_aqi['pm25'], errors='coerce')
df_aqi = df_aqi[['date', 'pm25']]
df_aqi.columns = ['Date', 'PM2.5']

df_merged = pd.merge(df_weather, df_aqi, on='Date', how='inner')
df_merged = df_merged.dropna(subset=['PM2.5'])

print(f"Data alignment successful. Total valid observations: {len(df_merged)}\n")

print("=== Step 2: Feature Engineering and Data Preprocessing ===")
X = df_merged[['Temperature', 'WindSpeed', 'Pressure', 'Precipitation']]
y = df_merged['PM2.5']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Preprocessing completed. Temporal variables strictly excluded.\n")

print("=== Step 3: Benchmarking Predictive Models ===")
models = {
    "Multiple Linear Regression": LinearRegression(),
    "Support Vector Regression": SVR(kernel='rbf'),
    "Random Forest Regressor": RandomForestRegressor(n_estimators=100, max_depth=5, random_state=42),
    "XGBoost Regressor": xgb.XGBRegressor(n_estimators=100, learning_rate=0.05, max_depth=3, random_state=42)
}

results = []
best_tree_model = None
best_tree_r2 = -float('inf')

for name, model in models.items():
    if name in ["Multiple Linear Regression", "Support Vector Regression"]:
        model.fit(X_train_scaled, y_train)
        y_pred = model.predict(X_test_scaled)
    else:
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)

    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    mae = mean_absolute_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    results.append({'Algorithm': name, 'R-squared': r2, 'RMSE': rmse, 'MAE': mae})

    if name in ["Random Forest Regressor", "XGBoost Regressor"]:
        if r2 > best_tree_r2:
            best_tree_r2 = r2
            best_tree_model = model

results_df = pd.DataFrame(results).round(4)
print("Table 1. Performance Evaluation of Machine Learning Models")
print("-" * 65)
print(results_df.to_string(index=False))
print("-" * 65 + "\n")

print("=== Step 4: SHAP (SHapley Additive exPlanations) Interpretability Analysis ===")
explainer = shap.TreeExplainer(best_tree_model)
shap_values = explainer.shap_values(X_test)

print("Generating Global Feature Importance Plot...")
plt.figure(figsize=(10, 6))
shap.summary_plot(shap_values, X_test, plot_type="bar", show=False)
plt.title("Global Feature Importance for PM2.5 Prediction (SHAP Values)")
plt.tight_layout()
plt.show()

print("\nGenerating Directional Impact Beeswarm Plot...")
plt.figure(figsize=(10, 6))
shap.summary_plot(shap_values, X_test, show=False)
plt.title("Directional Impact of Meteorological Drivers on PM2.5")
plt.tight_layout()
plt.show()

print("\nAnalysis sequence completed. Please save the new plots!")